"""empty message

Revision ID: 299ccd55c3f3
Revises: 
Create Date: 2023-03-06 16:46:44.541375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '299ccd55c3f3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('first_name')

    # ### end Alembic commands ###
